- doc/examples/searchlight.py
> term --> terms; amps --> maps

- mvpa2/misc/neighborhood.py
- mvpa2/tests/test_neighborhood.py
Added 'include_center' option HollowSphere to include center feature's data in the dataset sent to measures as first feature.
> NF: Added an option to include center feature in HollowSphere.

- mvpa2/clfs/libsvmc/svm.py
prediction was crashing when using ONE_CLASS svm
> fix estimates ca in case of ONE_CLASS svm

- .travis.yml
> ENH: at least if we still convert to python3 without problems

- mvpa2/base/dataset.py
- mvpa2/tests/test_datasetng.py
This is just to make the bug obvious. Fix needs to come.
> All equal broken

- mvpa2/tests/test_fxmapper.py
> BF+TST: do not use objectarray_equal for numerical comparisons

- mvpa2/misc/stats.py
> deal properly with NaN values in compute_ts_boxplot_stats

- mvpa2/tests/test_cosmo.py
Adresses #229 for recent versions of numpy/scipy on Mac OSX and Neurodebian.
>  bf/cosmo test build matlab cell

- Changelog
minor PR just to let you guys know @PyMVPA/developers  that we have it ;)
> DOC: ChangeLog entry on match/select

- mvpa2/datasets/mri.py
tested on that windows box -- surf test passes now
> BF: workaround for an issue with scl_ fields being nan on Windows, breaking comparison

- mvpa2/base/__init__.py
- mvpa2/clfs/dummies.py
- mvpa2/clfs/gda.py
- mvpa2/clfs/gnb.py
- mvpa2/clfs/knn.py
- mvpa2/clfs/libsvmc/svm.py
- mvpa2/clfs/smlr.py
- mvpa2/clfs/warehouse.py
- mvpa2/tests/test_clf.py
squeezing too far when dataset is one-class.
> fix for one-class (GLQ)DA

- mvpa2/__init__.py
- mvpa2/base/config.py
- mvpa2/base/info.py
- mvpa2/base/report.py
- mvpa2/clfs/libsmlrc/__init__.py
- mvpa2/datasets/sources/native.py
- mvpa2/misc/fsl/flobs.py
- mvpa2/misc/fsl/melodic.py
- mvpa2/misc/support.py
- mvpa2/support/afni/afni_surface_alphasim.py
- mvpa2/support/afni/afni_utils.py
- mvpa2/support/afni/lib_prep_afni_surf.py
- mvpa2/support/afni/suma_setup_instacorr.py
- mvpa2/support/nibabel/afni_suma_spec.py
- mvpa2/support/nibabel/surf_caret.py
- mvpa2/testing/datasets.py
- mvpa2/testing/regress.py
- mvpa2/tests/test_atlases.py
- mvpa2/tests/test_eepdataset.py
- mvpa2/tests/test_hdf5.py
- mvpa2/tests/test_iohelpers.py
- mvpa2/tests/test_meg.py
- mvpa2/tests/test_niftidataset.py
- mvpa2/tests/test_openfmri.py
- mvpa2/tests/test_surfing_afni.py
- mvpa2/tests/test_surfing_voxelselection.py
- mvpa2/tests/test_viz.py
- mvpa2/tutorial_suite.py
Addresses #312. @hanke, @yarikoptic, any vetos?
> use "pathjoin" instead of "os.path.join"

- mvpa2/algorithms/group_clusterthr.py
- mvpa2/tests/test_group_clusterthr.py
Should be ready to go in, but may still get some changes during real-world testing.
> Few small enhancements to the group cluster threshold code.

- mvpa2/cmdline/cmd_ofmotionqc.py
- mvpa2/cmdline/cmd_searchlight.py
- mvpa2/datasets/sources/openfmri.py
- mvpa2/misc/plot/base.py
- mvpa2/tests/test_openfmri.py
Not sure why the previous one was merged in a broken state. But I took the freedom to make it a bit more flexible.
> BF+ENH+DOC: An actually working motion QC plot command

- mvpa2/datasets/niml.py
- mvpa2/support/nibabel/afni_niml.py
- mvpa2/tests/test_surfing_afni.py
> Support AFNI NIML surface data without node indices

- mvpa2/algorithms/hyperalignment.py
- mvpa2/tests/test_hyperalignment.py
> BF: Fixed the logic in checking that ref_ds param is in the correct range

- mvpa2/base/dochelpers.py
- mvpa2/base/hdf5.py
- mvpa2/testing/sweep.py
- mvpa2/tests/test_hdf5.py
there is a bit of PEP8ing etc mixed in, sorry about that.
Closes #335
> Support storing into HDF5 ndarrays with unicodes

- mvpa2/measures/adhocsearchlightbase.py
- mvpa2/testing/tools.py
- mvpa2/tests/test_testing.py
- mvpa2/tests/test_usecases.py
gnbsearchlight now would digest errorfx=None, and now pass cvfolds, targets to the result dataset
> Improved comparison of datasets in tests, make gnbsearchlight more inline with regular Searchlight

- doc/examples/searchlight_surf.py
- mvpa2/datasets/gifti.py
- mvpa2/suite.py
- mvpa2/testing/tools.py
- mvpa2/tests/test_giftidataset.py
- mvpa2/tests/test_testing.py
- support GIFTI i/o for PyMVPA datasets
- adds new test function "assert_datasets_almost_equal"
> add basic GIFTI support

- mvpa2/base/config.py
- mvpa2/base/externals.py
Let's wait for travis since locally I got failures -- yet to figure out if my code or not
> RF(PEP8 etc): in externals code, to modernize it a bit as well

- mvpa2/datasets/cosmo.py
- mvpa2/tests/test_cosmo.py
minor NF to support CoSMoMVPA export of data in tuples in dataset .a. Also minor PEP8 cleanup thanks to PyCharm.
> support exporting tuple values from dataset .a to cosmo

- Makefile
- mvpa2/algorithms/benchmarks/__init__.py
- mvpa2/algorithms/benchmarks/hyperalignment.py
- mvpa2/base/__init__.py
- mvpa2/mappers/svd.py
- mvpa2/support/lapack_svd.py
- mvpa2/tests/test_benchmarks_hyperalignment.py
Was cherry-picked (with few other minor fixups) from a secrete hide-out to not die off and become actually useful ;)
> Hyper benchmarks -- movie time segment classification

- .travis.yml
This may fix an issue with travis hanging during coverage testing (#368).
@yarikoptic @hanke, any objections?
> ENH: use more recent mdp. 

- mvpa2/tests/test_surfing_afni.py
> BF+TST: support testing NIML I/O on 32-bit platforms

- doc/source/_themes/pymvpa_online/layout.html
> WEB: remove google analytics script in documentation layout theme

- doc/source/installation.rst
Since I have no clue in macports -- I could be utterly wrong.  @nno?
> DOC: adjust macports instructions. (Thanks Piotr T.)

- mvpa2/algorithms/hyperalignment.py
- mvpa2/generators/permutation.py
- mvpa2/mappers/som.py
- mvpa2/tests/test_generators.py
- mvpa2/tests/test_som.py
git commit  became annoyingly dilligent about trailing spaces
recently, so to minimize friction I have decided to fix them up
> ENH: removed some trailing spaces and fixed some typos

- .travis.yml
- Changelog
- mvpa2/__init__.py
- mvpa2/algorithms/group_clusterthr.py
- mvpa2/algorithms/hyperalignment.py
- mvpa2/clfs/__init__.py
- mvpa2/clfs/_svmbase.py
- mvpa2/clfs/lars.py
- mvpa2/clfs/libsvmc/svm.py
- mvpa2/clfs/sg/svm.py
- mvpa2/clfs/smlr.py
- mvpa2/clfs/transerror.py
- mvpa2/featsel/rfe.py
- mvpa2/measures/searchlight.py
- mvpa2/support/due.py
probably not for merge yet although should do no harm! ;)
it would result in following behavior (if duecredit is installed) if I e.g. run tests which invoke some "cited" functionality in sklearn (requires similarly patched sklearn) and pymvpa
```bash
> DUECREDIT_ENABLE=yes nosetests -s mvpa2/tests/test_clf.py mvpa2/tests/test_transerror.py
...
> duecredit summary               
DueCredit Report:
- mvpa2 (v None) [1]
- mvpa2.clfs.transerror._call (Bayesian hypothesis testing) [4]
- sklearn (v None) [3]
- sklearn.ensemble.forest.fit (None) [2]
2 modules cited
2 functions cited
References
----------
[1] Hanke, M. et al., 2009. PyMVPA: a Python Toolbox for Multivariate Pattern Analysis of fMRI Data. Neuroinform, 7(1), pp.37–53.
[2] Breiman, L., 2001. Random Forests. In Machine Learning. pp. …
```
> WiP+ENH: Added duecredit stub and few citations

- mvpa2/suite.py
@nno -- should be safe, right?
> BF: import SurfaceQueryEngine into suite

- 3rd/libsvm/COPYRIGHT
- 3rd/libsvm/README
- 3rd/libsvm/svm.cpp
- 3rd/libsvm/svm.h
- Changelog
so hopefully would resolve the stalls
> BF: updated bundled version of libsvm to 3.12 -- now carries maxiter

- mvpa2/base/__init__.py
- mvpa2/tests/test_fxmeasure.py
> BF minor fixes to please daily tests a bit

- mvpa2/generators/partition.py
- mvpa2/tests/test_generators.py
With code from Yarik who created it in an afternoon of madness. Docstring still WIP, submitted to track it. Unittest is simply a check against the old chain of nfoldpartitioner and sifter.
> ENH,WIP: add FactorialPartitioner to allow hierarchical cv

- mvpa2/measures/anova.py
> BF: Achieve Numpy 1.10 compatibility (fixes gh-381)

- mvpa2/algorithms/group_clusterthr.py
- mvpa2/generators/permutation.py
- mvpa2/misc/support.py
- mvpa2/testing/tools.py
- mvpa2/tests/test_generators.py
- mvpa2/tests/test_support.py
- mvpa2/tests/test_usecases.py
+ there is an additional commit with a little usecase test relying on that feature
> ENH: allow limit for AttributePermutator to be a list

- mvpa2/clfs/smlr.py
- mvpa2/generators/permutation.py
- mvpa2/tests/test_mapper.py
I really don't know why daily tests didn't fail on test_smlr.py before!
> BF: two minor bugfixes (skip if no nibabel, condition debug call) + some PEP8 of smlr.py

- mvpa2/datasets/cosmo.py
- mvpa2/tests/test_cosmo.py
> WIP+ENH: CoSMoMVPA i/o improvements

- Changelog
- mvpa2/measures/adhocsearchlightbase.py
- mvpa2/measures/nnsearchlight.py
- mvpa2/tests/test_searchlight.py
As demanded by Sam, so for him to try/review/fix/improve
> ENH: m1nn searchlight can now do correlation distance

- .travis.yml
- mvpa2/base/externals.py
- mvpa2/clfs/libsvmc/_svm.py
- mvpa2/clfs/libsvmc/svm.py
- mvpa2/tests/test_svm.py
> BF: disable testing against MDP master for now, compatibility with recent swig 3.x

- mvpa2/tests/test_rfe.py
minor-- will merge if tests pass
> ENH: additional testing of SplitRFE

- doc/source/whoisusingit.rst
just a start. the list is long.
> DOC: Who is using it.

- doc/examples/rsa_fmri.py
Updated the plotting range to [0,2] to reflect the range of correlation distances. This created confusion in one user. Also fixed a few typos while I am at it. @hanke @yarikoptic
> DOC: update matrix plot range to clear confusion, and fixed a few typos

- mvpa2/misc/surfing/queryengine.py
Addresses issue #457 
@nno any objections to this change?
> DOC: Changed volume geometry warning to print dataset instead of dumping the dataset

- mvpa2/misc/surfing/queryengine.py
- mvpa2/tests/test_surfing.py
Adds SurfaceRingQueryEngine for surfaces similar to HollowSphere,
with tests and some PEP8 formatting for test_surfing.
@nno @yarikoptic
> NF: Adds SurfaceRingQueryEngine for surfaces similar to HollowSphere

- mvpa2/tests/test_transerror.py
> BF: reduce required ACC while testing auc -- ran 100 times without failure

- mvpa2/featsel/rfe.py
- mvpa2/tests/test_rfe.py
> ENH: simplify SplitRFE doc example to nore require errorfx + reorder mappers

- mvpa2/tests/test_searchlight_hyperalignment.py
Addresses issue #455 
HT to @nno
> BF: Relaxed tests a little to account for noisy/correlated features

- mvpa2/misc/surfing/queryengine.py
> DOC: update documentation to properly reflect supported input type

- mvpa2/support/nibabel/surf.py
minor bug fix with computing ico linear divisions & minor improvment with determining multiples
> Minor fix and improvment

- mvpa2/generators/partition.py
- mvpa2/misc/support.py
- mvpa2/tests/test_generators.py
- mvpa2/tests/test_support.py
as desired on the mailing list by Basil
implementation is probably suboptimal but should be functional.  Noone in a sane mind should use equidistant anyways whenever large number of products between partitionings is expected
did some other minor touches around the code
> ENH: random and equidistant strategies for FactorialPartitioner

- setup.py
will be merged asap if tests pass
> BF: ulgy hack borrowed from NumPy to overcome pip's problem to work with 2to3ed code

- mvpa2/support/scipy/stats.py
might need more fixes, let's run it!
I have also tried to enabled installation of most recent scipy within travis one of the "matrix" env, but failed.  we would need to establish some full miniconda based one at some point. So for now this change will not be really tested
Closes #489
> BF: compatibility with scipy 0.18.0

- mvpa2/base/node.py
- mvpa2/generators/permutation.py
- mvpa2/generators/resampling.py
- mvpa2/misc/support.py
- mvpa2/tests/test_generators.py
- mvpa2/tests/test_support.py
Or should we name it 'random_state' to more inline with scikit.learn and actual beast it returns, @hanke -- what you think?
Closes: #492
> ENH: provide Balancer with rng= argument, provide get_rng helper

- mvpa2/tests/__init__.py
> Add missing tests to __init__.py

- mvpa2/algorithms/hyperalignment.py
- mvpa2/tests/test_hyperalignment.py
Added checks to make sure the input is a list of datasets. If not, the current version assumes each sample as a dataset and continues as usual. Current version also craps out if only a single dataset is used for training. @yarikoptic @mih
> Minor BFs in Hyperalignment with tests

- mvpa2/tests/test_surfing_surface.py
Incorporates #510 and adds test
> TST+BF: Fix a bug with computing edge lengths and add test

- mvpa2/algorithms/hyperalignment.py
- mvpa2/tests/test_hyperalignment.py
joblib based parallelization of last stage of Hyperalignment.
@yarikoptic @feilong
> NF: Parallelizing last step of Hyperalignment using joblib

- mvpa2/base/dochelpers.py
- mvpa2/base/hdf5.py
- mvpa2/clfs/libsvmc/sens.py
- mvpa2/misc/support.py
- mvpa2/testing/tools.py
- mvpa2/tests/test_fxmapper.py
- mvpa2/tests/test_surfing_surface.py
- mvpa2/tests/test_surfing_voxelselection.py
needs more work, contributions are welcome -- not sure if I will have more time for it tomorrow.  hopefully didn't break anything (yet)
> BF: patchwork to make pymvpa usable with python3 again

- mvpa2/misc/io/base.py
- mvpa2/support/nibabel/afni_niml.py
- mvpa2/support/nibabel/surf_gifti.py
> BF: do not use io.FileIO for writing, only for reading 

- doc/source/conf.py
- doc/sphinxext/exercise_directive.py
not sure if I did anything correctly ;) but at least docs build again
> Few fixes for recent sphinx deprecation etc

- Changelog
- mvpa2/misc/plot/base.py
- mvpa2/suite.py
- mvpa2/tests/__init__.py
- mvpa2/tests/test_misc_plot.py
If tests pass, will merge and release -- we need a new release to resolve those numpy upgrade issues
> TST for a forgotten plot function + changelog

- mvpa2/base/info.py
- mvpa2/misc/plot/base.py
- mvpa2/misc/plot/scatter.py
- mvpa2/testing/tools.py
- mvpa2/tests/test_base.py
- mvpa2/tests/test_hdf5.py
- mvpa2/tests/test_hdf5_clf.py
- mvpa2/tests/test_hyperalignment.py
- mvpa2/tests/test_misc_plot.py
- mvpa2/tests/test_misc_scatter.py
- mvpa2/tests/test_surfing.py
- Fixes #554   (at least partially ;) yet to address some remaining ones)
- Fixes #546 (IIRC)
> A variety of fixes to make tests pass across all the builds for conda-forge recipe

- mvpa2/tests/test_procrust.py
Using the explicit tests by @yarikoptic .
Fixes another bug with the new tests.
> ENH & FIX for Procrustes

- bin/pymvpa2
- mvpa2/base/externals.py
- mvpa2/mappers/wavelet.py
> Minor fixups

- mvpa2/base/collections.py
not sure if even covered by tests -- to be seen
> BF?ENH?: sort the unique values in the alternative handling of .unique

- mvpa2/misc/plot/scatter.py
- mvpa2/tests/test_misc_scatter.py
to overcome FTBFS in debian, conda and also ref: https://github.com/numpy/numpy/issues/10496
> Making scatter more robust

- mvpa2/measures/searchlight.py
- mvpa2/misc/surfing/queryengine.py
Closes #575  by just calling a bug a feature, via adjusting documentation
> Minor docs/code tune up for searchlight on surface

- mvpa2/algorithms/connectivity_hyperalignment.py
As described in this paper
http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1006120
> Added connectivity hyperalignment to algorithms.

- mvpa2/algorithms/connectivity_hyperalignment.py
- mvpa2/base/__init__.py
Some minor error fixes for CHA when running with `MVPA_DEBUG=CHPAL.*`.
> Connectivity Hyperalignment log issue

- bin/pymvpa2-tutorial
> Convert bytes output of subprocess to string for Python 3
