mvpa2/mappers/procrustean.py, mvpa2/tests/test_procrust.py
although probably doesn't make algorithmic sense it is probably the cleanest way to conform to super class'es desire to have demean option
=> BF: do not demean in procrustean if demean=False (Close #276)

mvpa2/misc/neighborhood.py, mvpa2/tests/test_neighborhood.py
Neighborhood such that `neighbors(i) == [i]`.
Perhaps there already exists a way of doing this (apart from, say, `Sphere(0.5)`), but since it was easier for me to write this than dig deeper into the code, I figured it might be useful for others to have something big and obvious.
=> ENH Add identity neighborhood

tools/rst2ipnbpy
ran into problems while trying to convert slides for Python course of Per
e.g.
http://memory.osu.edu/classes/python/_sources/lessons/lsn01.txt
Not sure if that  -1 is due, but was needed.
It also misses handling tables tags so for processing Per's lesson, just remove those tables
I wish we had tests for this beast ;)
=> BF: rst2ipnbpy - more unique temp string for \n, fixing first_line

mvpa2/datasets/eventrelated.py
Please merge this. Forcing the inclusion of the GLM model (as we do now) makes this unusable for the forrets gump data -- I need some 70+ GB for a simple 3 regressor fit. With this change, I can do it with 68GB less ;-)
=> ENH: Prevent potentially excessize memory use by default.

mvpa2/support/afni/afni_surface_alphasim.py
This PR addresses a question on the PyMVPA mailing list [1].
For surface-based analysis, if an anatomical surface file is not specified, a more informative error message is provided. 
In addition, this PR fixes some whitespace issues following PEP8.
[1] http://lists.alioth.debian.org/pipermail/pkg-exppsy-pymvpa/2015q2/003092.html
=> ENH: afni_surface_alphasim: provide more informative error message 

mvpa2/clfs/meta.py, mvpa2/tests/test_clf.py
truncated labels occurs in case of labels being string array with variable length and first predicted is shorter
guessing dtype from learned labels set instead
=> fix label bug in TreeClassifier

COPYING, doc/source/contributors.txt
Very minor update for copyright year (2014 -> 2015)  and affiliation. 
@hanke, @yarikoptic, are there new contributors we should add?
=> MSC: update copyright and developer info to reflect current state

mvpa2/datasets/mri.py, mvpa2/tests/test_niftidataset.py, tools/strip_nibabel
I finally arrived (cognitively) at the location that @nno was already at yesterday. Here is a simple RF that centralizes the bits introduced yesterday.
=> RF+TST+DOC: Single strip_nibabel() to take care of dtype conversion

mvpa2/tests/test_fxmapper.py
=> BF+PEP8: Reduce memory demand for MeanRemoval mapper test

mvpa2/misc/support.py, mvpa2/testing/regress.py, mvpa2/testing/tools.py, mvpa2/tests/test_support.py, mvpa2/tests/test_testing.py
got broken due to recent renames
to fix first Travis failure had to make SmartVersion explicitly convert unicode in versions to str
all for good! ;)
=> BF+NF+ENH: assert_datasets_equal (stub) + test_generate_testing_fmri_dataset

mvpa2/tests/test_surfing.py
=> TST+ENH: use the filename provided by @with_tempfile decorator

mvpa2/mappers/procrustean.py, mvpa2/tests/test_procrust.py
instead of computing inverse (as part of super class)
This should be faster and possibly avert any numerical errors that might creep up during numpy.linalg.inv()
=> ENH: Procrustean mapper now returns transpose as inverse

mvpa2/datasets/niml.py, mvpa2/support/nibabel/afni_niml.py, mvpa2/support/nibabel/afni_niml_types.py, mvpa2/tests/test_surfing_afni.py
Following issue #335 raised by @swaroopgj, and PR #339 by @yarikoptic which adds unicode support to h5{save,load}, this PR adds a test for Unicode data for NIML datasets.
At also includes the PEP8 recommendations made in #336. (Apologies for mixing in the  PEP8 stuff, PyCharm was a bit aggressive.)
=> tests for NIML unicode support

mvpa2/datasets/niml.py, mvpa2/tests/test_surfing_afni.py
Fixes an issue uncovered by #328 which added more stringent tests for dataset equality, causing test_surfing_afni.py to fail [1]. The unit test now also cleans up a temporary file after use.
[1] https://travis-ci.org/PyMVPA/PyMVPA/builds/71774997
=> set dataset attributes coming from NIML as vectors, not matrices (if possible)

mvpa2/datasets/cosmo.py, mvpa2/tests/test_cosmo.py
Minor changes to allow for an .origin element. The current implementation simply ignores it presence.
=> ENH: support origin element in CoSMoMVPA neighbors element

mvpa2/generators/permutation.py, mvpa2/tests/test_generators.py
without this raise, it would crash on the next line with "TypeError: 'NoneType' object is not iterable" msg
=> added more informative error msg

mvpa2/measures/anova.py
According to [SciPy 0.16.0 Release Notes](https://github.com/scipy/scipy/blob/6aa03af69897582f290045b26b3a374b9fda29c0/doc/release/0.16.0-notes.rst#backwards-incompatible-changes), fprob was deprecated in version 0.16 and replaced with `special.fdtrc`, according to https://github.com/scipy/scipy/issues/2741.
I'm not sure if the term `fprob` should be replaced with `fdtrc` throughout PyMVPA.
=> FIX: replaces deprecated fprob from scipy.stats with special.fdtrc

mvpa2/mappers/som.py, mvpa2/tests/test_som.py
There are two main changes:
-The Kohonen layer is updated with each sample, not just on each iteration. This prevents an issue where if the learning rate * the number of sample was > 1, the Kohonen layer was driven to extreme values.
-The Kohonen layer now has periodic boundaries. This is introduced through precomputing the influence array, then rolling it to the appropriate location for each sample.
(-) a new variable, self._dqdshape, is introduced to make computing the influence layer faster, as it now only needs to be calculated once per iteration and its shape does not change.
Both of these changes have a new test in test_som.py
Hopefully this helps! Apologies if I've done anything wrong, I'm quite new to github.
=> SOM bug fix and periodic boundary conditions

mvpa2/datasets/gifti.py, mvpa2/support/nibabel/surf.py, mvpa2/tests/test_giftidataset.py
This PR improves GIFTI support for functional data and fixes a bug:
- The GIFTI standard is not very clear about the presence of a coordinate matrix for data-arrays that are not point-sets, but FreeSurfer's mris_convert doesn't like their presence. This PR sets these coordinate matrices to None so that they are not stored.
- When storing functional data, is is cast to float32. Similarly, node indices are stored as int32
- map2gifti supports a "surface" argument to store anatomical information, so that FreeSurfer's mris_convert can deal with GIFTI files written by map2gifti
=> ENH+BF: improve GIFTI functional data mapping support

mvpa2/misc/surfing/volume_mask_dict.py, mvpa2/tests/test_surfing_voxelselection.py
When using surface-based voxel selection, sometimes auxiliary attributes in the VolumeMaskDict have different but compatible datatypes (such as float32 and float64). This PR allows for saving such VolumeMaskDict objects.
Thanks to @swaroopgj for reporting the issue.
This PR also includes some code cleanup following PEP8 guidelines.
=> support VolumeMaskDict with different but compatible datatypes

mvpa2/algorithms/group_clusterthr.py, mvpa2/tests/test_group_clusterthr.py, mvpa2/tests/test_usecases.py
We wanted to use parts of the implementation for similar cluster level thresholding but without bootstraps and other thrills.  While going through the logic, spotted one point to discuss (how cluster sizes get accumulated, around the point when [0] is returned) and provided few helper functions to work with those Counter's stats on cluster sizes collected, so they could be used easily to estimate p values for non-bootstrapped results.
=> Expose some functionality of group_clusterthr so could be used independently of the GroupClusterThreshold

mvpa2/tests/test_mapper.py
Two tests to demonstrate a problem with "adjusted" StaticFeatureSelection
- in first case it raises exception demanding training (IMHO shouldn't)
- in the 2nd case, with a ChainMapper it pretty much skips any reverse mapping
=> WiP TST(BK): two use-case tests showing problems with adjusted StaticFeatureSelection

mvpa2/measures/anova.py, mvpa2/tests/test_datameasure.py
also OPT to use some inplace operations without temporary arrays being created
Since I haven't seen my concerns in https://github.com/PyMVPA/PyMVPA/pull/400 being addressed before/after merge and otherwise I would have forgotten.
Also added comparison against scipy implementation (which we should've just used at this point I guess)
=> BF+ENH: explicitly use float for "sum of" estimation in anova so we get proper float division

mvpa2/generators/partition.py, mvpa2/measures/adhocsearchlightbase.py, mvpa2/measures/base.py, mvpa2/tests/test_clfcrossval.py, mvpa2/tests/test_searchlight.py
generator=None  primarily to facilitate cross- classifications, so people could just specify
a Splitter on the values of the necessary attribute and be done
Also includes a bugfix for ad-hoc searchlights (such as gnbsearchlight) which disallowed to use custom partitioners which return more than 2 partitions.  While at it also made them work with a custom Splitter.
=> ENH: make partitioner (aka generator) optional for CrossValidation and ad-hoc searchlights

mvpa2/base/dataset.py, mvpa2/tests/test_datasetng.py
To ease data exchange with non-pymvpa-savvy users
One tricky part is that savez uses TEMPDIR so if dataset is large -- saving might fail if /tmp is not ample enough:  https://github.com/numpy/numpy/issues/5336
=> NF: to/from_npz for Datasets

mvpa2/base/externals.py, mvpa2/datasets/sources/openfmri.py, mvpa2/tests/test_openfmri.py
also added datalad external, if crawled openfmri ds 105 is present - smoke testing above
fix on it
also no dedicated unittest etc I would prefer to merge this one asap so ppl could start using OpenFMRIDataset construct with actual openfmri datasets.
=> BF+ENH: set TR from scan_key for openfmri datasets' with TR=1 in nifti files

mvpa2/datasets/cosmo.py, mvpa2/tests/test_cosmo.py
WiP for #430 (@mvdoc @snastase). This first step allows exporting an fMRI dataset created in PyMVPA to CoSMoMVPA.
TODO for this PR: update CoSMoMVPA's ``cosmo_fmri_dataset`` so that the resulting struct can be read in CoSMoMVPA directly.
Roadmap: 
- implement i/o for the reverse way, i.e. allow an fmri dataset from CoSMoMVPA to be imported in PyMVPA, and be recognized as nifti-like frmi-dataset
- to do same for surface-based data (bi-directional)
=> NF: support to export NIFTI to CoSMo format

Makefile
on OSX, the syntax::
rsync HOST::SRC1 HOST::SRC2 TRG 
is not supported; instead::
rsync HOST::'SRC1 SRC2' TRG
must be used. This PR updates the ``fetch-data`` option in the Makefile that used the unsupported syntax.
(Unfortunately I did not find a way to split the source line into multiple lines)
=> ENH: use rsync syntax compatible with what is present on OSX

mvpa2/tests/test_searchlight.py
just a tiny bit, but still:
```
> python -c 'import numpy as np; d = np.random.normal(size=(100, 100)).astype(np.float64); print (np.max(np.corrcoef(d)) - 1.0)'
2.22044604925e-16
```
so causes tests to fail.  yet to check if master numpy fixed
=> BF(workaround): numpy 1:1.11.0~b3-1+b1 manages to get corrcoef > 1

mvpa2/tests/test_transerror.py
since we ruined our ad-hoc support for it in adf13478a4628c0f04b63eabd1cb405d45175a7d
=> ENH: skip testing AUC on KNN based classifiers 

mvpa2/clfs/libsvmc/_svm.py, mvpa2/tests/test_svm.py
May be added few not really needed double free ups 'just incase' and a
unittest for the leak.   Thanks Laurens Berthold (@bertholdl) for the very nice report
=> BF: free up svm model's vectors correctly (Closes #443)

mvpa2/misc/surfing/volume_mask_dict.py
VolumeMaskDictionary's __repr__ object, as the full output may result in a significant slow-down of the __repr__ method. Thanks to @swaroopgj for suggesting a fix for this.
=> OPT: show only summary of representation of internal _src2aux

mvpa2/algorithms/searchlight_hyperalignment.py, mvpa2/tests/test_searchlight_hyperalignment.py
- Featsel if given as proportion, selects featsel*(nfeatures of ref_ds)
- Adds test to break current version on master without this fix
- Make sure the mapper are intitialized with correct shape
- Make sure roi_seed is not used, and feature corresponding to that seed is selected
when queryengines are surface-to-voxel maps.
@yarikoptic can you please review these changes?
=> Few bug fixes to handle feature selection, roi_seed, and datasets with different features

doc/examples/hyperalignment.py
Using alpha values for regularized hyperalignment that don't fail for numpy SVD implementation.
=> BF: Fixing hyperalignment example so that it doesn't crash without lapack

mvpa2/algorithms/searchlight_hyperalignment.py, mvpa2/tests/test_searchlight_hyperalignment.py
When training Hyperalignment, `ref_ds` refers to the index of the reference
Dataset in the training set (after excluding Datasets), which is consistent
with the documentation.
In some other places, the same variable is used as the index of the referece
Dataset in the full set (before excluding Datasets), and that could cause
mismatch issues.
=> BF: ref_ds indexing issue when used with exclude_from_model

mvpa2/algorithms/hyperalignment.py, mvpa2/tests/test_searchlight_hyperalignment.py
Rather a workaround than a proper fix (to serialize and save lambdas, at least the ones without closures)
Closes #491
=> BF: replace lambdas with defined helper functions to allow to h5save hyperalignments

mvpa2/measures/rsa.py, mvpa2/tests/test_rsa.py
This implements cross-validated RSA.
Adds CDist as a measure that will eventually be passed to `CrossValidation` to get cvRSA.
With help from @mvdoc @snastase @feilong
=> ENH: Basic implementation of cross-validation rsm using learner and CV.

mvpa2/support/afni/lib_prep_afni_surf.py
=> BF: remove extra double quote in cmd for MapIcosahedron

mvpa2/algorithms/hyperalignment.py, mvpa2/tests/test_hyperalignment.py
As originally published in Haxby et al. (2014), dimensionality reduction using SVD is added after Hyperalignment with extra parameter `output_dim` as input. 
If output_dim is specified, HPAL computes projection to SV space derived from training datasets in addition to mappers to the `ref_ds` space.
@yarikoptic @mih
=> NF: Added dimensionality reduction using SVD to Hyperalignment.

setup.py
Note: it is still not perfect because it still assumes that `numpy` is installed, but it is less trivial than I thought to make it work—especially for the compiling of libsvm.
=> ENH: add required packages to setup.py

mvpa2/base/state.py, mvpa2/base/verbosity.py, mvpa2/clfs/blr.py, mvpa2/clfs/distance.py, mvpa2/clfs/libsvmc/_svm.py, mvpa2/clfs/meta.py, mvpa2/clfs/similarity.py, mvpa2/clfs/transerror.py, mvpa2/datasets/miscfx.py, mvpa2/featsel/rfe.py, mvpa2/measures/irelief.py, mvpa2/misc/io/base.py, mvpa2/misc/plot/base.py, mvpa2/misc/plot/erp.py, mvpa2/misc/plot/scatter.py, mvpa2/support/_emp_null.py, mvpa2/support/afni/afni_utils.py, mvpa2/support/nibabel/afni_suma_1d.py, mvpa2/support/nibabel/surf_fs_asc.py, mvpa2/tests/test_datameasure.py, mvpa2/tests/test_giftidataset.py, mvpa2/tests/test_iohelpers.py, mvpa2/tests/test_splitter.py, tools/bib2rst_ref.py
-  commit 391acd8463d23b171f7fb32731f6a015de8265f4
BF(thanks stringent numpy):  deal with a composite mask (one per x, one per y) for scatter_plot
before numpy allowed the selection mask being smaller than actual
array, e.g.
np.arange(5)[np.array([True, False, True])]
which is not entirely kosher.  And in our case if both masks were
provided it did something not entirely kosher I think
Now it should join both masks into intersection first
- commit 97141ed3f7a538fef3bfa19c9653e80bdfa8adfe
BF(RF): == None -> is None, != None -> is not None
seems that numpy 1.13.1 stopped tollerating comparing to None and made
it uniform comparison per each element... so if we would like to really
compare if anything was set, use "is" not "==" with None
=> Bf numpy1.13.1

mvpa2/misc/errorfx.py, mvpa2/tests/test_errorfx.py
In case of the disbalanced sets of samples, mean of the TPR is a more robust measure, which should be `1/n_classes` by chance (unlike the mean accuracy error which would jump between `1/n_classes` and some number defined by the proportion of samples in the dominating samples class).  I could be wrong, but according to my "notes" from few years back (http://www.pymvpa.org/files/OHBM2015_Halchenko.pdf) some toolkits (PRoNTo, PROBID, TDT) already use it as the main error function to avoid such problems while dealing with disbalanced sets.  In case of the balanced sets, it should produce the same error/accuracy as the mean_accuracy
=> NF: mean_tpr and mean_fnr errorfxs (might be a better default)

mvpa2/algorithms/hyperalignment.py, mvpa2/tests/test_hyperalignment.py
If this looks good to you I'll also update `searchlight_hyperalignment.py` to make similar changes to SL HA. @yarikoptic @swaroopgj
=> Add parameter to allow equal weight during HPAL level 1 iteration.

mvpa2/mappers/procrustean.py, mvpa2/tests/test_procrust.py
The transformation matrix `T` is transposed when reflection is turned off.
The scaling factor `scale` is also incorrect in this case because `s` is modified during the corresponding if statement.
The new test should fail in such cases.
=> Fix issues with Procrustes transformation

mvpa2/base/hdf5.py
h5lib 1.10 and beyond lock a file if any process reads or writes it (complete description is here: https://support.hdfgroup.org/HDF5/docNewFeatures/SWMR/Design-HDF5-FileLocking.pdf).
A typical PyMVPA script often has an `h5save()` call at the end to store results. With this new locking behavior, we make a single attempt to save and the entire script crashes if there was a concurrent access at that particular time. This leads to desperation, anger, and unicorns dying each time is happens.
This PR introduces re-trying to obtain a file handler in case it was reported as locked. The present implementation tries a fixed maximum number of 30 times, one second apart. This is of course arbitrary and will not fix the issue in case of large files being written that are also open for read, etc... …
=> ENH: Robustify h5save() in the presence of file locks

mvpa2/support/afni/lib_plot_slices.py
Would fix #574. 
- converting to float32 necessary for matplotlib >=  2.0.0
- set_axis_bgcolor deprecated in 2.0.0, removed in 2.2.0
=> make prep-afni-surf compatible with matplotlib >=2.0.0

mvpa2/algorithms/connectivity_hyperalignment.py, mvpa2/suite.py, mvpa2/tests/test_connectivity_hyperalignment.py
This is a basic test that ensures ISC of connectivity profiles increases after CHA for both training and testing data of a "subject".
Each subject's data contains 4 ROIs of 3 vertices each, and the 3 vertices have both shared and idiosyncratic responses to mimic the spatially coarse- and fine-scale information of fMRI data.
It seems I cannot modify the original PR, so I am creating a new PR for this.
=> Add unittest to CHA

mvpa2/generators/resampling.py, mvpa2/tests/test_generators.py
Following on #493, I've found these useful for debugging and verification of Balancer selections.
Example usage:
``` Python
balancer = Balancer(..., apply_selection=False)
logger = LogExclusions(log_file)
partitioner = ChainNode([NFoldPartitioner(), balancer, logger, ApplySelection()],
space='partitions')
```
Any interest in including either of these?
=> NF: Log and apply selections

mvpa2/datasets/mri.py, mvpa2/tests/test_niftidataset.py
Original comment hinted that it was supposed to be set by nibabel if provided
affine is None.  I have tested in precise docker image with nibabel 1.1.0 (2011ish)
and it (already) was not the case.  So better to set it explicitly and test for
that in the tests.  Thanks @ddwagner for the report and analysis!
Closes #599
=> BF: set affine to the one we know in map2nifti

mvpa2/base/hdf5.py, mvpa2/misc/attrmap.py, mvpa2/misc/data_generators.py, mvpa2/tests/test_hdf5.py
This generalizes the logic and thus unicode labels would also be mapped,
as well as any other odd type.  Use unicode labels for normal_feature_dataset
Closes #604
=> BF: AttributeMap -- consider only int (+unsigned) and float to be numeric labels

mvpa2/clfs/gnb.py, mvpa2/clfs/libsvmc/sens.py, mvpa2/clfs/meta.py, mvpa2/datasets/base.py, mvpa2/mappers/fx.py, mvpa2/support/_emp_null.py, mvpa2/tests/test_datameasure.py, mvpa2/tests/test_fxmapper.py, mvpa2/tests/test_gnb.py, mvpa2/tests/test_multiclf.py
- GNB had sensitivity negated
- make GNB `has_sensitivity` added in constructor so we discover/test it from the warehouse
- test that MulticlassClassifier's sensitivity would match the one produced by the classifier directly
- make order of targets for BinaryClassifier also be (neg, pos)
- make libsvm's SVM produce tuples of pairs even when no attrmap was assigned (SG one was doing that already)
- more ...
=> A variety of fixes to make target pairs consistently object array of tuples with (neg, pos) targets

mvpa2/clfs/gnb.py, mvpa2/tests/test_clf.py, mvpa2/tests/test_gnb.py
we ~~mitigate~~ try to avoid it by offseting all the values by the maximal value (in log space),
computing marginals, and then offsetting back when back in the logspace.
Similar strategy should be possible for operating in original, non logspace.
But may be there is even a better way, so not bothering for now.
Attn @dinga92 , sorry it took so long ;)
Also the most recent change by @adswa  who introduced the test for GNB sensitivites with an evil scenario of no variance in one of the features, and `MVPA_DEBUG=ENFORCE_CA_ENABLED` triggering it lead to another fix/workaround for those cases.
Closes #581
=> BF: guard against under/overflows and mitigate in case of logprob=True (default)

mvpa2/base/externals.py, mvpa2/datasets/eventrelated.py, mvpa2/datasets/miscfx.py, mvpa2/tests/test_datasetfx.py, mvpa2/tests/test_erdataset.py
Decided to make into an independent helper although probably could be used/invoked as part of the `fit_event_hrf_model`
attn @adswa
Bonus bundle: `.to_df` `@datasetmethod` to convert any Dataset to pandas data frame for at least some humane display of the dataset.  `.a` are get ignored, and `.sa`, `.fa` establish index and columns correspondingly.  So for a quick view at your dataset, just e.g.
```
(Pdb) get_contrasts(evds, contrasts={'face-house': {'face': 1, 'house': -1}}).to_df()
fa.voxel_indices   [0 3 4]   [0 3 5]   [0 4 4]
sa.targets                                    
face-house       -2.948647  1.933818  5.084473
```
although some would come out quite more elaborate ;)
```
*(Pdb) p ds.to_df()
fa.voxel_indices …
```
=> ENH(BK): prototype for get_contrasts to obtain contrasts for fit NiPy GLM model

.travis.yml, mvpa2/tests/test_giftidataset.py
This PR tries to address recent travis build errors, which started at
https://travis-ci.org/PyMVPA/PyMVPA/builds/545881884
with commit 
https://github.com/PyMVPA/PyMVPA/commit/2617c4d8dfe3fbe9e53f8e703ea996ab937b5c8f
although the root cause of the failing tests is probably a change in the default Ubunto configuration used on travis rather than code changes in PyMVPA.
=> BLD: for travis, set language to java and use trusty as distribution

mvpa2/testing/tools.py
Otherwise we get
```
In [1]: from mvpa2.suite import *
Failed to import duecredit due to No module named 'duecredit'
/Users/mvdoc/bin/anaconda3/lib/python3.7/site-packages/mvpa2/misc/surfing/volume_mask_dict.py:24: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
from collections import Mapping
ds = niml/Users/mvdoc/bin/anaconda3/lib/python3.7/site-packages/nose/importer.py:12: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
from imp import find_module, load_module, acquire_lock, release_lock
---------------------------------------------------------------------------
ModuleNotFoundError …
```
=> FIX import of skipif for newer versions of numpy

doc/examples/pylab_2d.py, doc/source/datadb/forrestgump_audio.rst, mvpa2/mappers/mdp_adaptor.py, mvpa2/measures/base.py, mvpa2/misc/surfing/volgeom.py, mvpa2/support/nibabel/surf.py
There are small typos in:
- doc/examples/pylab_2d.py
- doc/source/datadb/forrestgump_audio.rst
- mvpa2/mappers/mdp_adaptor.py
- mvpa2/measures/base.py
- mvpa2/misc/surfing/volgeom.py
- mvpa2/support/nibabel/surf.py
Fixes:
- Should read `neighborhood` rather than `neighboorhood`.
- Should read `arbitrary` rather than `arbitray`.
- Should read `latitude` rather than `latitute`.
- Should read `indices` rather than `indidces`.
- Should read `hemisphere` rather than `hemispehre`.
- Should read `facilitate` rather than `faciliate`.
- Should read `classifier` rather than `clasifier`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: Fix a few typos
